[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' app.netlify.com; child-src 'self' app.netlify.com; script-src 'self' app.netlify.com netlify-cdp-loader.netlify.app;"
